name: ml
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip==20.3.3
  - pandas==1.2.1
  - nltk==3.5
  - scikit-learn==0.24.1
  - joblib==1.0.0
  - scipy==1.6.0
  - threadpoolctl==2.0.0
  - pydub==0.25.1
  - pip:
      - textstat==0.7.0
      - lexicalrichness==0.1.3
      - textblob==0.15.3
      - numpy==1.19.2
      - tensorflow==2.4.1
      - tensorflow-gpu==2.4.1
      - tensorflow-hub==0.11.0
      - tensorflow-datasets==4.2.0
      - h5py==2.10.0
      - pyyaml==5.4.1
      - keras-tuner==1.0.2

