name: ml
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip==20.3.3
  - tensorflow==2.2.0
  - pandas==1.2.1
  - nltk==3.5
  - scikit-learn==0.24.1
  - joblib==1.0.0
  - scipy==1.6.0
  - threadpoolctl==2.0.0
  - pip:
      - textstat==0.7.0
      - lexicalrichness==0.1.3
      - textblob==0.15.3
      - numpy==1.20.1
      - tensorflow==2.4.1
      - tensorflow-gpu==2.4.1
      - tensorflow-hub==0.11.0

